package xml;

/**
 * Enumération des TypesRequete possibles
 *
 */
public enum TypeRequete
{
	ENVOI_EVENEMENT,
	ENVOI_DEPENSE,
	ENVOI_UTILISATEUR,
	CONNEXION,
	INCONNU,
	ENVOI_MESSAGE,
	ENVOI_PARTICIPE,
	DEMANDE_CHAT,
	DEMANDE_EVENEMENT,
	DEMANDE_DEPENSE,
	DEMANDE_UTILISATEUR,
	DEMANDE_PARTICIPEUTILISATEUR
}
